name: Executar Job

on:
  workflow_dispatch:
    inputs:
      numeroInteiro:
        description: "Quantos quartos gerar? "
        required: true
        default: 1

jobs:
  executar-gerar-quartos:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_ORG: ${{ secrets.OPENAI_ORG }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Instalar dependências
        run: npm install

      - name: Executar node index.ts
        run: npm start -- -n ${{ github.event.inputs.numeroInteiro }}
